// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZlNszUyVaLZv3fq3Ouj00AcVJgakSmww',
    appId: '1:372625435433:web:a45c9519b4dddb645be538',
    messagingSenderId: '372625435433',
    projectId: 'greentrekker-b7598',
    authDomain: 'greentrekker-b7598.firebaseapp.com',
    storageBucket: 'greentrekker-b7598.appspot.com',
    measurementId: 'G-PRX9N96CW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodkgppegsxdzxIesznbU_qXR8Re6KmQQ',
    appId: '1:372625435433:android:00685a0583e79b265be538',
    messagingSenderId: '372625435433',
    projectId: 'greentrekker-b7598',
    storageBucket: 'greentrekker-b7598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwMXwyeFUC74mJmmPsp9Apb-R9lOoaV4',
    appId: '1:372625435433:ios:c6ee29754cbd796d5be538',
    messagingSenderId: '372625435433',
    projectId: 'greentrekker-b7598',
    storageBucket: 'greentrekker-b7598.appspot.com',
    iosBundleId: 'com.example.gfgEcotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTwMXwyeFUC74mJmmPsp9Apb-R9lOoaV4',
    appId: '1:372625435433:ios:c6ee29754cbd796d5be538',
    messagingSenderId: '372625435433',
    projectId: 'greentrekker-b7598',
    storageBucket: 'greentrekker-b7598.appspot.com',
    iosBundleId: 'com.example.gfgEcotech',
  );
}
